# Docker Compose

version: '3'

services:
  mysql:
    container_name: toy3-mysql
    image: mysql:8.0
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: ${LOCAL_MYSQL_ROOT_PASSWORD}
      MYSQL_USERNAME: ${LOCAL_MYSQL_USERNAME}
      MYSQL_PASSWORD: ${LOCAL_MYSQL_PASSWORD}
      MYSQL_DATABASE: fc_sns
      TZ: Asia/Seoul
    volumes:
      - ${LOCAL_MYSQL_VOLUME_PATH}:/var/lib/mysql
    ports:
      - ${LOCAL_MYSQL_PORT}:3306
  # 레디스 추가?
  redis:
    image: redis:7.2
    ports: # 바인딩할 포트:내부 포트
      - ${LOCAL_REDIS_PORT}:6379
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes: # 마운트할 볼륨 설정
      - ${LOCAL_REDIS_VOLUME_PATH}:/data
      - ${LOCAL_REDIS_CONFIG_PATH}:/usr/local/etc/redis/redis.conf
    restart: always
